### ISSUE TITLE
0.2.8 pip pypi source package

### ISSUE THREAD

**Issue by cederom** [ARMmbed/cmsis-pack-manager#112] opened 2019-05-31 19:13 UTC
Hello @theotherjimmy so much THANK YOU for your work on build fixes and 0.2.8 release. The release sources build fine from the release source files! :-) Could you please provide source package to the pypi so we can download and install CPM with pip? :-)

```
(venv36bsd) 0xCFC2% pip install cmsis-pack-manager
Collecting cmsis-pack-manager
  Using cached https://files.pythonhosted.org/packages/5e/1f/9368d142276d6305f92236d64ddc8cc7f41fd0781e9a6380d65ab36d898e/cmsis-pack-manager-0.1.0.tar.gz
Requirement already satisfied: appdirs>=1.4 in /ztuff/cederom/usr/local/venv36bsd/lib/python3.6/site-packages (from cmsis-pack-manager) (1.4.3)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /ztuff/cederom/usr/local/venv36bsd/lib/python3.6/site-packages (from cmsis-pack-manager) (4.6.3)
Collecting fuzzywuzzy>=0.10.0 (from cmsis-pack-manager)
  Using cached https://files.pythonhosted.org/packages/d8/f1/5a267addb30ab7eaa1beab2b9323073815da4551076554ecc890a3595ec9/fuzzywuzzy-0.17.0-py2.py3-none-any.whl
ERROR: pyocd 0.21.0 has requirement cmsis-pack-manager>=0.2.7, but you'll have cmsis-pack-manager 0.1.0 which is incompatible.
Installing collected packages: fuzzywuzzy, cmsis-pack-manager
  Running setup.py install for cmsis-pack-manager ... done
Successfully installed cmsis-pack-manager-0.1.0 fuzzywuzzy-0.17.0


(venv36bsd) 0xCFC2% pip install cmsis-pack-manager==0.2.8
Collecting cmsis-pack-manager==0.2.8
  ERROR: Could not find a version that satisfies the requirement cmsis-pack-manager==0.2.8 (from versions: 0.1.0)
ERROR: No matching distribution found for cmsis-pack-manager==0.2.8


(venv36bsd) 0xCFC2% pip install cmsis-pack-manager==
Collecting cmsis-pack-manager==
  ERROR: Could not find a version that satisfies the requirement cmsis-pack-manager== (from versions: 0.1.0)
ERROR: No matching distribution found for cmsis-pack-manager==
```

**Comment by theotherjimmy** [comment] 2019-05-31 19:16
Duplicate of #91. Yeah, sure. I can add it to PyPi.

**Closed** 2019-05-31 19:16 UTC
